version: '3'
services:
  skyshi1ginapi:
      container_name: skyshi1gin_api
      build: ./
      ports: 
        - 8091:8091 
      restart: on-failure
      depends_on:
        - fullstack-mysql           # Uncomment this when using mysql.
      networks:
        - skyshi1gin_network
  fullstack-mysql:
    platform: linux/x86_64
    image: mysql:8.0.28
    container_name: skyshi1gin_mysql
    ports: 
      - ${DB_PORT}:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - skyshi1gin_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skyshi1gin_phpmyadmin
    depends_on:
      - fullstack-mysql
    environment:
      - PMA_HOST=fullstack-mysql # Note the "mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=${DB_USER}
      - PMA_PORT=3306
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DOC_PHPMYADMIN_PORT}:80
    restart: always
    networks:
      - skyshi1gin_network

volumes:
  database_mysql:                   # Uncomment this when using mysql.

# Networks to be created to facilitate communication between containers
networks:
  skyshi1gin_network:
    driver: bridge