@host = http://localhost:8901/api/v1

# @name login
POST {{host}}/user/login HTTP/1.1
Content-Type: application/json

{
    "identifier": "denieskresna@gmail.com",
    "password": "cobacobadoang"
}

###
@token = {{login.response.body.responseData.token}}

# @name createOrder
POST {{host}}/order/purchase HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

[
    {
        "product_id": 1,
        "amount": 6
    }
]

###
# @name orderPayment
POST {{host}}/order/pay HTTP/1.1
Content-Type: application/json
Authorization: paymentgatewaytoken

{
    "code": "fGielipYbWOVdyBKKQof"
}
